name: Continuous

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: "vs2017-win2016"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: "Build Release"
      shell: bash
      run: |
        mkdir EleDo
        mv target/release/eledo.exe target/release/eledo-pty-bridge.exe target/release/normdo.exe EleDo/
        cp README.md LICENSE.md EleDo
        cd EleDo
        7z a -tzip ../EleDo.zip *
    - name: "Upload artifact"
      uses: actions/upload-artifact@master
      with:
         name: "EleDo"
         path: "EleDo.zip"
    - name: "Upload to Continuous Release"
      uses: wez/upload-release-assets@releases/v1
      with:
         files: "EleDo.zip"
         release-tag: "Continuous"
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: "Generate artifact hashes"
      run: |
        sha256sum *.zip | tee hashes.txt
    - name: "Upload artifact hashes"
      uses: actions/upload-artifact@master
      with:
         name: "hashes"
         path: "hashes.txt"
